#!/usr/bin/env python3
# =============================================================================
#  build_wl_model_81.py   (Plan 81 - Paid-Up Whole Life)
# -----------------------------------------------------------------------------
#  Rebuilds the workbook from ONLY two CSV inputs:
#         1) Inputs.csv     (label,value  - one policy)
#         2) cso_rates.csv  (mortality rate matrix)
#
#  Design (same as the Plan-34 builder):
#    * 12 sheets: CSO Rates, Inputs, MORTALITY, Commutation, CV_RATES,
#      PUA_TABLE, DIvidend_Assumption, Projection_Monthly, RPU, ETI, APL, Loan.
#    * CSO Rates  = cso_rates.csv read into a DataFrame and pasted as-is
#                   (only row 4's CONCAT codes are formulas). NOTHING hardcoded.
#    * Inputs     = keeps ONLY columns A, B, D, E (description/legend columns
#                   C and F..S are dropped). Column B is driven by Inputs.csv,
#                   so a different policy just runs with its own numbers.
#    * every other sheet is pure formulas referencing those two sheets.
#
#  NOTE - external link fix:
#    The reference file's MORTALITY column C used '[2]ETI!$B$7' - a link to a
#    SECOND workbook (the Plan-34 file), which discounted at 2.5% instead of
#    this policy's own 2.75%. A self-contained model cannot resolve an external
#    file, so every '[2]ETI!$B$7' has been localized to 'ETI!$B$7' (this
#    workbook), i.e. it now discounts at the policy's own accumulation rate.
#
#  Repeated (fill-down) formulas are written with a LOOP: for each column the
#  origin formula is translated down every row exactly like Excel fill-down
#  (relative refs shift, absolute $refs stay, integer counters increment).
#
#  MODEL_SPEC per sheet:
#     "statics"  : {coord: value}            labels, headers, constants
#                                            (CSO Rates has NONE - it's the CSV)
#     "arrays"   : [coords]                  cells entered as array formulas
#     "fills"    : [ [col, r0, r1, kind, origin_formula, counter_positions] ]
#         kind "trans"   : fill origin_formula from r0 down to r1 (refs shift)
#         kind "counter" : same, then bump integer literal(s) at the given
#                          positions by (row - r0)   e.g.  +1-1, +2-1, +3-1 ...
#         kind "lit"     : write origin_formula verbatim (array formulas)
#     "colfmt"/"fmt_exc" : number formats      "widths": column widths
#  Dates in "statics" are stored as ["__dt__", "ISO"] so they round-trip.
#
#  Usage:
#     pip install openpyxl pandas
#     python build_wl_model_81.py                                  # defaults
#     python build_wl_model_81.py Inputs.csv cso_rates.csv out.xlsx
# =============================================================================
import sys, csv, re, datetime
import pandas as pd
from openpyxl import Workbook
from openpyxl.utils import get_column_letter
from openpyxl.formula.translate import Translator
from openpyxl.worksheet.formula import ArrayFormula

INPUTS_CSV = sys.argv[1] if len(sys.argv) > 1 else "Inputs.csv"
CSO_CSV    = sys.argv[2] if len(sys.argv) > 2 else "cso_rates.csv"
OUT_XLSX   = sys.argv[3] if len(sys.argv) > 3 else "WL_Model_Paidup_81.xlsx"

SHEET_ORDER = ['CSO Rates','Inputs','MORTALITY','Commutation','CV_RATES','PUA_TABLE',
               'DIvidend_Assumption','Projection_Monthly','RPU','ETI','APL','Loan']

# =============================================================================
#  Fill / helper engine
# =============================================================================
_INT = re.compile(r'(?<![A-Za-z$0-9_.])\d+')

def _bump_ints(s, positions, delta):
    out, last = [], 0
    for i, m in enumerate(_INT.finditer(s)):
        if i in positions:
            out.append(s[last:m.start()]); out.append(str(int(m.group()) + delta)); last = m.end()
    out.append(s[last:]); return ''.join(out)

def _translate(formula, origin, dest):
    """Excel fill-down: shift relative refs from origin cell to dest cell."""
    return Translator(formula, origin=origin).translate_formula(dest)

def _dec(v):
    if isinstance(v, list) and len(v) == 2 and v[0] == "__dt__":
        return datetime.datetime.fromisoformat(v[1])
    return v

def _cell(x):
    """Type a raw CSV string: '' -> None, integer -> int, else float, else str."""
    if x is None: return None
    x = str(x).strip()
    if x == "" or x.lower() == "nan": return None
    try:
        i = int(x)
        if str(i) == x: return i
    except ValueError: pass
    try: return float(x)
    except ValueError: return x

def _coerce(raw, ref):
    """Coerce a CSV input string to match the reference cell's python type."""
    raw = (raw or "").strip()
    if raw == "": return None
    if isinstance(ref, list) and len(ref) == 2 and ref[0] == "__dt__":            # date
        for fmt in ("%d-%m-%Y", "%Y-%m-%d", "%m/%d/%Y", "%d/%m/%Y"):
            try: return datetime.datetime.strptime(raw, fmt)
            except ValueError: pass
        return raw
    if isinstance(ref, bool):
        return raw.upper() in ("TRUE", "1", "YES")
    pct = raw.endswith("%")
    num = raw[:-1] if pct else raw
    if isinstance(ref, float) or pct:
        try: return float(num) / 100.0 if pct else float(num)
        except ValueError: return raw
    if isinstance(ref, int):
        try: return int(float(num))
        except ValueError: return raw
    return raw                                                                    # string, e.g. "3802170L"

# =============================================================================
#  CSV loaders
# =============================================================================
def load_inputs(path):
    d = {}
    with open(path, newline="") as f:
        for row in csv.reader(f):
            if row and row[0].strip():
                d[row[0].strip()] = row[1] if len(row) > 1 else ""
    return d

def load_cso_df(path):
    return pd.read_csv(path, header=None, dtype=str, keep_default_na=False)

# =============================================================================
#  Sheet writer
# =============================================================================
def write_sheet(ws, name, spec, inputs=None, cso_df=None):
    written = set()
    def put(coord, value):
        ws[coord] = value
        written.add(coord)

    # ---- 1) CSO Rates : paste the DataFrame straight in (NOTHING hardcoded) --
    if name == "CSO Rates":
        for _, row in cso_df.iterrows():
            ws.append([_cell(v) for v in row.tolist()])
        for r in range(1, ws.max_row + 1):
            for c in range(1, ws.max_column + 1):
                if ws.cell(row=r, column=c).value is not None:
                    written.add(f"{get_column_letter(c)}{r}")
    else:
        # ---- 2) static cells (labels, headers, constants) -------------------
        for coord, val in spec["statics"].items():
            put(coord, _dec(val))

    # ---- 3) formula fills : LOOP each column's origin formula down its rows --
    arrays = set(spec.get("arrays", []))
    for col, r0, r1, kind, f0, pos in spec["fills"]:
        origin = f"{col}{r0}"
        for r in range(r0, r1 + 1):
            coord = f"{col}{r}"
            if kind == "lit":
                formula = f0
            elif kind == "trans":
                formula = _translate(f0, origin, coord)
            else:  # counter
                formula = _bump_ints(_translate(f0, origin, coord), pos, r - r0)
            put(coord, ArrayFormula(coord, formula) if coord in arrays else formula)

    # ---- 4) Inputs sheet : override column-B values from the policy CSV ------
    if name == "Inputs" and inputs is not None:
        for r in range(1, ws.max_row + 1):
            label = ws[f"A{r}"].value
            bcoord = f"B{r}"
            if label in inputs and bcoord in spec["statics"]:   # only genuine inputs
                v = _coerce(inputs[label], spec["statics"][bcoord])
                if v is not None:
                    ws[bcoord] = v

    # ---- 5) number formats + column widths ----------------------------------
    colfmt, exc = spec.get("colfmt", {}), spec.get("fmt_exc", {})
    for coord in written:
        col = re.match(r"[A-Z]+", coord).group()
        fmt = exc.get(coord, colfmt.get(col))
        if fmt:
            ws[coord].number_format = fmt
    for col, w in spec.get("widths", {}).items():
        ws.column_dimensions[col].width = w

# =============================================================================
def main():
    inputs = load_inputs(INPUTS_CSV)
    cso_df = load_cso_df(CSO_CSV)
    wb = Workbook(); wb.remove(wb.active)
    for name in SHEET_ORDER:
        print(f"  building sheet: {name}")
        write_sheet(wb.create_sheet(title=name), name, MODEL_SPEC[name], inputs=inputs, cso_df=cso_df)
    wb.save(OUT_XLSX)
    print(f"\nSaved: {OUT_XLSX}")
    print("Open in Excel to recalculate. Summarised outputs = Inputs!D2:E7")
    print("(Cash Value, PUA Cash Value, ETI, RPU, APL, Loan Outstanding).")


# =============================================================================
#  MODEL DEFINITION  (fully editable - every formula & constant is below)
# =============================================================================
MODEL_SPEC = {
  'CSO Rates': {
    "statics": {},
    "arrays": [],
    "fills": [
      ['B', 4, 4, 'trans', '=_xlfn.CONCAT(B1,B2,B3)', []],
      ['C', 4, 4, 'trans', '=_xlfn.CONCAT(C1,C2,C3)', []],
      ['D', 4, 4, 'trans', '=_xlfn.CONCAT(D1,D2,D3)', []],
      ['E', 4, 4, 'trans', '=_xlfn.CONCAT(E1,E2,E3)', []],
      ['F', 4, 4, 'trans', '=_xlfn.CONCAT(F1,F2,F3)', []],
      ['G', 4, 4, 'trans', '=_xlfn.CONCAT(G1,G2,G3)', []],
      ['H', 4, 4, 'trans', '=_xlfn.CONCAT(H1,H2,H3)', []],
      ['I', 4, 4, 'trans', '=_xlfn.CONCAT(I1,I2,I3)', []],
      ['J', 4, 4, 'trans', '=_xlfn.CONCAT(J1,J2,J3)', []],
      ['K', 4, 4, 'trans', '=_xlfn.CONCAT(K1,K2,K3)', []],
      ['L', 4, 4, 'trans', '=_xlfn.CONCAT(L1,L2,L3)', []],
      ['M', 4, 4, 'trans', '=_xlfn.CONCAT(M1,M2,M3)', []],
      ['N', 4, 4, 'trans', '=_xlfn.CONCAT(N1,N2,N3)', []],
      ['O', 4, 4, 'trans', '=_xlfn.CONCAT(O1,O2,O3)', []],
      ['P', 4, 4, 'trans', '=_xlfn.CONCAT(P1,P2,P3)', []],
    ],
    "colfmt": {},
    "fmt_exc": {},
    "widths": {'A': 8.73},
  },
  'Inputs': {
    "statics": {
        'D1': 'Output',
        'A2': 'Mortality Table',
        'B2': 41,
        'D2': 'Cash Value',
        'A3': 'Underwriting Class',
        'B3': 'X',
        'D3': 'PUA Cash Value',
        'A4': 'Plan Code',
        'B4': 81,
        'D4': 'ETI',
        'A5': 'Policy Number',
        'B5': '3802170L',
        'D5': 'RPU',
        'A6': 'Gender',
        'B6': 'M',
        'D6': 'APL',
        'A7': 'Issue Age',
        'D7': 'Loan Outstanding',
        'A8': 'Paid-Up Age',
        'B8': 85,
        'A9': 'Units',
        'B9': 5,
        'A10': 'PUA Units',
        'B10': 0.558,
        'A11': 'Issue Date',
        'B11': ['__dt__', '1961-03-27T00:00:00'],
        'A12': 'Valuation Date',
        'B12': ['__dt__', '2026-03-27T00:00:00'],
        'A13': 'Last Anniversary',
        'A14': 'DOB',
        'B14': ['__dt__', '1934-07-06T00:00:00'],
        'A15': 'Current age',
        'D15': 'Age at Valuation Date',
        'A16': 'Duration(x)',
        'D16': 'Policy Duration (complete years)',
        'A17': 'Duration(x+1)',
        'D17': 'Duration for next anniversary',
        'A18': 'Base SA',
        'A19': 'Declared Dividend (After Conv Date)',
        'B19': 0,
        'A20': 'Declared Dividend Rate (p.a.)',
        'B20': 0,
        'A21': 'Expense Loading Factor',
        'B21': 0.03,
        'A22': 'Dividend Option',
        'B22': 'PUA',
        'A23': 'Accumulation Interest Rate (p.a.)',
        'B23': 0.0275,
        'A24': 'Annual Base Premium',
        'B24': 0,
        'A25': 'Modal Premium',
        'A26': 'Premium Mode',
        'B26': 'Annual',
        'A27': 'Modal Factor',
        'A28': 'Contract Status',
        'B28': 'A',
        'D28': 'MAX(0, MIN(Paid-Up Age - Issue Age, Duration))',
        'A29': 'Premium Paid-Up Duration',
        'D29': 'TRUE if Current Age < Paid-Up Age',
        'A30': 'Is Currently Paying Premium',
        'A31': 'Loan Intrest Rate',
        'B31': 0.05,
        'A32': 'Loan Interest Type',
        'B32': 'A',
        'A33': 'Loan Start Date',
        'B33': ['__dt__', '2023-10-14T00:00:00'],
        'A34': 'Starting Loan Amount',
        'B34': 373.37,
        'A35': 'Loan Repayment Date',
        'A36': 'Repayment Amount',
    },
    "arrays": ['B27', 'E2', 'E3'],
    "fills": [
      ['B', 7, 7, 'trans', '=ROUND((B11-B14)/365.25,0)', []],
      ['B', 13, 13, 'trans', '=IF(DATE(YEAR($B$12),MONTH($B$11),MIN(DAY($B$11),\nDAY(EOMONTH(DATE(YEAR($B$12),MONTH($B$11),1),0))))\n<=$B$12,\nDATE(YEAR($B$12),MONTH($B$11),MIN(DAY($B$11),\nDAY(EOMONTH(DATE(YEAR($B$12),MONTH($B$11),1),0)))),\nDATE(YEAR($B$12)-1,MONTH($B$11),MIN(DAY($B$11),\nDAY(EOMONTH(DATE(YEAR($B$12)-1,MONTH($B$11),1),0)))))', []],
      ['B', 15, 15, 'trans', '=ROUND(YEAR(B13)-YEAR(B14)+(MONTH(B13)-MONTH(B14))/12+(DAY(B13)-DAY(B14)-1)/360,0)', []],
      ['B', 16, 16, 'trans', '=INT((B12-B11)/365.25)', []],
      ['B', 17, 17, 'trans', '=B16+1', []],
      ['B', 18, 18, 'trans', '=B9*1000', []],
      ['B', 25, 25, 'trans', '=B24*B27', []],
      ['B', 27, 27, 'lit', '=_xlfn.SWITCH(B26,"Annual",1,"Semi-Annual",0.5,"Quarterly",0.25,"Monthly",1/12,1)', []],
      ['B', 29, 29, 'trans', '=MAX(0, MIN(B8 - B7, B16))', []],
      ['B', 30, 30, 'trans', '=B15 < B8', []],
      ['E', 2, 2, 'lit', '=_xlfn.LET(\n    _xlpm.ValDate, $B$12,\n    _xlpm.DateRange, Projection_Monthly!$B$2:$B$1050,\n    _xlpm.CVRange, Projection_Monthly!$L$2:$L$1050,\n    _xlpm.ExactMatch, _xlfn.XLOOKUP(_xlpm.ValDate, _xlpm.DateRange, _xlpm.CVRange, "", 0),\n    IF(_xlpm.ExactMatch<>"", _xlpm.ExactMatch,\n        _xlfn.LET(\n            _xlpm.DateBefore, _xlfn.XLOOKUP(_xlpm.ValDate, _xlpm.DateRange, _xlpm.DateRange, "", -1),\n            _xlpm.DateAfter, _xlfn.XLOOKUP(_xlpm.ValDate, _xlpm.DateRange, _xlpm.DateRange, "", 1),\n            _xlpm.CVBefore, _xlfn.XLOOKUP(_xlpm.DateBefore, _xlpm.DateRange, _xlpm.CVRange),\n            _xlpm.CVAfter, _xlfn.XLOOKUP(_xlpm.DateAfter, _xlpm.DateRange, _xlpm.CVRange),\n            _xlpm.DaysBetween, _xlpm.DateAfter - _xlpm.DateBefore,\n            _xlpm.DaysFromBefore, _xlpm.ValDate - _xlpm.DateBefore,\n            _xlpm.Fraction, _xlpm.DaysFromBefore / _xlpm.DaysBetween,\n            _xlpm.CVBefore + _xlpm.Fraction * (_xlpm.CVAfter - _xlpm.CVBefore)\n        )\n    )\n)', []],
      ['E', 3, 3, 'lit', '=_xlfn.LET(\n    _xlpm.ValDate, $B$12,\n    _xlpm.DateRange, Projection_Monthly!$B$2:$B$1050,\n    _xlpm.CVRange, Projection_Monthly!$M$2:$M$1050,\n    _xlpm.ExactMatch, _xlfn.XLOOKUP(_xlpm.ValDate, _xlpm.DateRange, _xlpm.CVRange, "", 0),\n    IF(_xlpm.ExactMatch<>"", _xlpm.ExactMatch,\n        _xlfn.LET(\n            _xlpm.DateBefore, _xlfn.XLOOKUP(_xlpm.ValDate, _xlpm.DateRange, _xlpm.DateRange, "", -1),\n            _xlpm.DateAfter, _xlfn.XLOOKUP(_xlpm.ValDate, _xlpm.DateRange, _xlpm.DateRange, "", 1),\n            _xlpm.CVBefore, _xlfn.XLOOKUP(_xlpm.DateBefore, _xlpm.DateRange, _xlpm.CVRange),\n            _xlpm.CVAfter, _xlfn.XLOOKUP(_xlpm.DateAfter, _xlpm.DateRange, _xlpm.CVRange),\n            _xlpm.DaysBetween, _xlpm.DateAfter - _xlpm.DateBefore,\n            _xlpm.DaysFromBefore, _xlpm.ValDate - _xlpm.DateBefore,\n            _xlpm.Fraction, _xlpm.DaysFromBefore / _xlpm.DaysBetween,\n            _xlpm.CVBefore + _xlpm.Fraction * (_xlpm.CVAfter - _xlpm.CVBefore)\n        )\n    )\n)', []],
      ['E', 4, 4, 'trans', '=ETI!$E$6', []],
      ['E', 5, 5, 'trans', '=RPU!$B$17', []],
      ['E', 6, 6, 'trans', '=APL!$F$10', []],
      ['E', 7, 7, 'trans', '=IF(B32="D",VLOOKUP("Valuation",Loan!$C$28:$G$40,5,0),IF(B32="A",VLOOKUP("Valuation",Loan!$L$28:$P$40,5,0),"Not Found"))', []],
    ],
    "colfmt": {
        'E': '#,##0.00',
    },
    "fmt_exc": {
        'E4': 'mm-dd-yy',
        'E6': 'mm-dd-yy',
        'B11': 'mm-dd-yy',
        'B12': 'mm-dd-yy',
        'B13': 'mm-dd-yy',
        'B14': 'mm-dd-yy',
        'B20': '0.00%',
        'B21': '0.00%',
        'B23': '0.00%',
        'B24': '0',
        'B25': '0',
        'B31': '0.00%',
        'B33': 'mm-dd-yy',
    },
    "widths": {'A': 30.82, 'B': 17.54, 'D': 20.18, 'E': 11.82},
  },
  'MORTALITY': {
    "statics": {
        'A1': 'Age',
        'C1': 'v*qx',
        'D1': 'v*q(x+1)*px',
        'A2': 0,
    },
    "arrays": [],
    "fills": [
      ['A', 3, 123, 'trans', '=IFERROR(IF(B2>=1,"",A2+1),"")', []],
      ['B', 1, 1, 'trans', '=_xlfn.CONCAT(Inputs!B2,Inputs!B6,Inputs!B3)', []],
      ['B', 2, 123, 'trans', '=IFERROR(INDEX(\'CSO Rates\'!$A$5:$P$126,MATCH(A2,\'CSO Rates\'!$A$5:$A$126,0),MATCH($B$1,\'CSO Rates\'!$A$4:$P$4,0)),"")', []],
      ['C', 2, 123, 'trans', '=IFERROR(ETI!$B$7*B2,"")', []],
      ['D', 2, 123, 'trans', '=IFERROR(IF(A2="","",C2*(1-B3)),0)', []],
    ],
    "colfmt": {
        'B': '0.00000_)',
        'C': '0.00000_)',
        'D': '0.00000_)',
    },
    "fmt_exc": {
        'B1': 'General',
        'C1': 'General',
        'D1': 'General',
    },
    "widths": {'B': 11.18, 'C': 10.54, 'D': 12.91, 'F': 8.73},
  },
  'Commutation': {
    "statics": {
        'A1': 'Age',
        'B1': 'qx',
        'C1': 'lx',
        'D1': 'dx',
        'E1': 'v^x',
        'F1': 'Dx',
        'G1': 'Cx',
        'H1': 'Nx',
        'I1': 'Mx',
        'J1': 'ax_due',
        'K1': 'Ax',
        'L1': 'NLP_per_1000',
        'M1': 'LPP_NLP_per_1000',
        'A2': 0,
        'C2': 10000000,
    },
    "arrays": [],
    "fills": [
      ['A', 3, 102, 'trans', '=IF(OR(A2="",A2>=MAX(MORTALITY!$A:$A)),"",A2+1)', []],
      ['B', 2, 102, 'trans', '=IF(A2="","",IFERROR(INDEX(MORTALITY!$B:$B,MATCH(A2,MORTALITY!$A:$A,0)),0))', []],
      ['C', 3, 102, 'trans', '=IF(A3="","",IFERROR(C2*(1-B2),0))', []],
      ['D', 2, 102, 'trans', '=IF(A2="","",IFERROR(C2*B2,0))', []],
      ['E', 2, 102, 'trans', '=IF(A2="","",IFERROR((1/(1+Inputs!$B$23))^A2,0))', []],
      ['F', 2, 102, 'trans', '=IF(A2="","",IFERROR(C2*E2,0))', []],
      ['G', 2, 102, 'trans', '=IF(A2="","",IFERROR(D2*(1/(1+Inputs!$B$23))^(A2+1),0))', []],
      ['H', 2, 102, 'trans', '=IF(A2="","",IFERROR(IF(B2=1,F2,F2+H3),0))', []],
      ['I', 2, 102, 'trans', '=IF(A2="","",IFERROR(IF(B2=1,G2,G2+I3),0))', []],
      ['J', 2, 102, 'trans', '=IF(A2="","",IFERROR(H2/F2,0))', []],
      ['K', 2, 102, 'trans', '=IF(A2="","",IFERROR(I2/F2,0))', []],
      ['L', 2, 102, 'trans', '=IF(A2="","",IFERROR(1000*I2/H2,0))', []],
      ['M', 2, 102, 'trans', '=IF(A2="","",IFERROR(1000*I2/(H2-INDEX(H:H,MATCH(A2+Inputs!$B$8,$A:$A,0))),0))', []],
    ],
    "colfmt": {
        'B': '0.00000_)',
    },
    "fmt_exc": {
        'B1': 'General',
        'B102': 'General',
    },
    "widths": {'A': 9.45, 'B': 10.18, 'C': 11.82, 'L': 12.73, 'M': 16.54},
  },
  'CV_RATES': {
    "statics": {
        'A1': 'Code',
        'B1': 'Issue Age',
        'C1': 'Duration',
        'D1': 'Attained Age',
        'E1': 'qx',
        'F1': 'px',
        'G1': 'Interest Rate',
        'H1': 'Beta (NLP/1000)',
        'I1': 'CV (BOY)',
        'J1': 'CV (EOY)',
        'K1': 'CV FACTOR',
        'C2': 0,
        'I2': 0,
    },
    "arrays": [],
    "fills": [
      ['A', 2, 101, 'trans', '=IF(D2>100,"",Inputs!$B$4)', []],
      ['B', 2, 101, 'trans', '=IF(D2>100,"",Inputs!$B$7)', []],
      ['C', 3, 101, 'trans', '=IFERROR(IF(Inputs!$B$7+C2+1>=100,"",C2+1),"")', []],
      ['D', 2, 101, 'trans', '=IFERROR(IF(Inputs!$B$7+C2>=100,"",Inputs!$B$7+C2),"")', []],
      ['E', 2, 101, 'trans', '=IF(D2="","",INDEX(MORTALITY!$B:$B,MATCH(D2,MORTALITY!$A:$A,0)))', []],
      ['F', 2, 101, 'trans', '=IF(D2="","",1-E2)', []],
      ['G', 2, 101, 'trans', '=IF(D2="","",Inputs!$B$23)', []],
      ['H', 2, 101, 'trans', '=IF(D2="","",INDEX(Commutation!$L:$L,MATCH(Inputs!$B$7,Commutation!$A:$A,0)))', []],
      ['I', 3, 101, 'trans', '=IF(D3="","",J2)', []],
      ['J', 2, 101, 'trans', '=IF(D2>99,"",IF(E2=1,1000,MIN(1000,MAX(0,(INDEX(Commutation!$K:$K,MATCH(D3,Commutation!$A:$A,0))-(INDEX(Commutation!$K:$K,MATCH(Inputs!$B$7,Commutation!$A:$A,0))/((INDEX(Commutation!$H:$H,MATCH(Inputs!$B$7,Commutation!$A:$A,0))-INDEX(Commutation!$H:$H,MATCH(Inputs!$B$8,Commutation!$A:$A,0)))/INDEX(Commutation!$F:$F,MATCH(Inputs!$B$7,Commutation!$A:$A,0))))*MAX(0,(INDEX(Commutation!$H:$H,MATCH(D3,Commutation!$A:$A,0))-INDEX(Commutation!$H:$H,MATCH(Inputs!$B$8,Commutation!$A:$A,0)))/INDEX(Commutation!$F:$F,MATCH(D3,Commutation!$A:$A,0))))*1000))))', []],
      ['K', 2, 101, 'trans', '=J2', []],
    ],
    "colfmt": {
        'D': '0',
        'E': '0.00000_)',
        'F': '0.00000_)',
        'G': '0.00%',
    },
    "fmt_exc": {
        'D1': '0.00',
        'E1': 'General',
        'F1': 'General',
        'G1': 'General',
    },
    "widths": {'A': 7.36, 'B': 10.91, 'C': 10.45, 'D': 13.73, 'E': 8.0, 'G': 11.45, 'H': 14.27, 'I': 11.82},
  },
  'PUA_TABLE': {
    "statics": {
        'A3': 'Issue Age',
        'B3': 'Duration',
        'C3': 'Attained Age',
        'D3': 'PUA SP per $1 SA (Ax)',
        'E3': 'Dx',
        'F3': 'Nx+1',
        'G3': 'Mx',
        'H3': 'Beta (NLP/1000)',
        'I3': 'PUA CVF per 1000 (Fackler)',
    },
    "arrays": [],
    "fills": [
      ['A', 4, 103, 'counter', '=IF(Inputs!$B$7+1-1>MAX(MORTALITY!$A:$A),"",Inputs!$B$7)', [0]],
      ['B', 4, 103, 'counter', '=IF(Inputs!$B$7+1-1>MAX(MORTALITY!$A:$A),"",1)', [0, 2]],
      ['C', 4, 103, 'counter', '=IF(Inputs!$B$7+1-1>MAX(MORTALITY!$A:$A),"",Inputs!$B$7+1-1)', [0, 2]],
      ['D', 4, 103, 'trans', '=IF(C4="","",INDEX(Commutation!$K:$K,MATCH(C4,Commutation!$A:$A,0)))', []],
      ['E', 4, 103, 'counter', '=IF(Inputs!$B$7+1-1>MAX(MORTALITY!$A:$A),"",IFERROR(INDEX(Commutation!$F:$F,MATCH(C4,Commutation!$A:$A,0)),0))', [0]],
      ['F', 4, 103, 'counter', '=IF(Inputs!$B$7+1-1>MAX(MORTALITY!$A:$A),"",IFERROR(INDEX(Commutation!$H:$H,MATCH(C4+1,Commutation!$A:$A,0)),0))', [0]],
      ['G', 4, 103, 'counter', '=IF(Inputs!$B$7+1-1>MAX(MORTALITY!$A:$A),"",IFERROR(INDEX(Commutation!$I:$I,MATCH(C4,Commutation!$A:$A,0)),0))', [0]],
      ['H', 4, 103, 'counter', '=IF(Inputs!$B$7+1-1>MAX(MORTALITY!$A:$A),"",IFERROR(1000*INDEX(Commutation!$I:$I,MATCH(Inputs!$B$7,Commutation!$A:$A,0))/INDEX(Commutation!$H:$H,MATCH(Inputs!$B$7,Commutation!$A:$A,0)),0))', [0]],
      ['I', 4, 103, 'counter', '=IF(Inputs!$B$7+1-1>MAX(MORTALITY!$A:$A),"",IFERROR((1000*G4-H4*F4)/E4,0))', [0]],
    ],
    "colfmt": {
        'C': '0',
        'D': '0.000',
        'E': '_(* #,##0.00_);_(* \\(#,##0.00\\);_(* \\-??_);_(@_)',
        'F': '_(* #,##0.00_);_(* \\(#,##0.00\\);_(* \\-??_);_(@_)',
        'G': '_(* #,##0.00_);_(* \\(#,##0.00\\);_(* \\-??_);_(@_)',
        'H': '_(* #,##0.00_);_(* \\(#,##0.00\\);_(* \\-??_);_(@_)',
        'I': '_(* #,##0.00_);_(* \\(#,##0.00\\);_(* \\-??_);_(@_)',
    },
    "fmt_exc": {
        'C3': 'General',
        'D3': 'General',
        'E3': 'General',
        'F3': 'General',
        'G3': 'General',
        'H3': 'General',
        'I3': 'General',
    },
    "widths": {'B': 9.18, 'C': 8.82, 'D': 15.18, 'E': 14.0, 'F': 14.54, 'G': 12.54, 'H': 11.45, 'I': 17.27},
  },
  'DIvidend_Assumption': {
    "statics": {
        'B1': 'Age',
        'A2': 'Duration',
        'B2': 0,
        'A3': 0,
    },
    "arrays": [],
    "fills": [
      ['A', 4, 103, 'trans', '=A3+1', []],
      ['B', 3, 3, 'trans', '=Inputs!$B$20', []],
      ['B', 4, 103, 'trans', '=B3', []],
      ['C', 2, 2, 'trans', '=+B2+1', []],
      ['C', 3, 103, 'trans', '=B4', []],
      ['D', 2, 2, 'trans', '=+C2+1', []],
      ['D', 3, 103, 'trans', '=C4', []],
      ['E', 2, 2, 'trans', '=+D2+1', []],
      ['E', 3, 103, 'trans', '=D4', []],
      ['F', 2, 2, 'trans', '=+E2+1', []],
      ['F', 3, 103, 'trans', '=E4', []],
      ['G', 2, 2, 'trans', '=+F2+1', []],
      ['G', 3, 103, 'trans', '=F4', []],
      ['H', 2, 2, 'trans', '=+G2+1', []],
      ['H', 3, 103, 'trans', '=G4', []],
      ['I', 2, 2, 'trans', '=+H2+1', []],
      ['I', 3, 103, 'trans', '=H4', []],
      ['J', 2, 2, 'trans', '=+I2+1', []],
      ['J', 3, 103, 'trans', '=I4', []],
      ['K', 2, 2, 'trans', '=+J2+1', []],
      ['K', 3, 103, 'trans', '=J4', []],
      ['L', 2, 2, 'trans', '=+K2+1', []],
      ['L', 3, 103, 'trans', '=K4', []],
      ['M', 2, 2, 'trans', '=+L2+1', []],
      ['M', 3, 103, 'trans', '=L4', []],
      ['N', 2, 2, 'trans', '=+M2+1', []],
      ['N', 3, 103, 'trans', '=M4', []],
      ['O', 2, 2, 'trans', '=+N2+1', []],
      ['O', 3, 103, 'trans', '=N4', []],
      ['P', 2, 2, 'trans', '=+O2+1', []],
      ['P', 3, 103, 'trans', '=O4', []],
      ['Q', 2, 2, 'trans', '=+P2+1', []],
      ['Q', 3, 103, 'trans', '=P4', []],
      ['R', 2, 2, 'trans', '=+Q2+1', []],
      ['R', 3, 103, 'trans', '=Q4', []],
      ['S', 2, 2, 'trans', '=+R2+1', []],
      ['S', 3, 103, 'trans', '=R4', []],
      ['T', 2, 2, 'trans', '=+S2+1', []],
      ['T', 3, 103, 'trans', '=S4', []],
      ['U', 2, 2, 'trans', '=+T2+1', []],
      ['U', 3, 103, 'trans', '=T4', []],
      ['V', 2, 2, 'trans', '=+U2+1', []],
      ['V', 3, 103, 'trans', '=U4', []],
      ['W', 2, 2, 'trans', '=+V2+1', []],
      ['W', 3, 103, 'trans', '=V4', []],
      ['X', 2, 2, 'trans', '=+W2+1', []],
      ['X', 3, 103, 'trans', '=W4', []],
      ['Y', 2, 2, 'trans', '=+X2+1', []],
      ['Y', 3, 103, 'trans', '=X4', []],
      ['Z', 2, 2, 'trans', '=+Y2+1', []],
      ['Z', 3, 103, 'trans', '=Y4', []],
      ['AA', 2, 2, 'trans', '=+Z2+1', []],
      ['AA', 3, 103, 'trans', '=Z4', []],
      ['AB', 2, 2, 'trans', '=+AA2+1', []],
      ['AB', 3, 103, 'trans', '=AA4', []],
      ['AC', 2, 2, 'trans', '=+AB2+1', []],
      ['AC', 3, 103, 'trans', '=AB4', []],
      ['AD', 2, 2, 'trans', '=+AC2+1', []],
      ['AD', 3, 103, 'trans', '=AC4', []],
      ['AE', 2, 2, 'trans', '=+AD2+1', []],
      ['AE', 3, 103, 'trans', '=AD4', []],
      ['AF', 2, 2, 'trans', '=+AE2+1', []],
      ['AF', 3, 103, 'trans', '=AE4', []],
      ['AG', 2, 2, 'trans', '=+AF2+1', []],
      ['AG', 3, 103, 'trans', '=AF4', []],
      ['AH', 2, 2, 'trans', '=+AG2+1', []],
      ['AH', 3, 103, 'trans', '=AG4', []],
      ['AI', 2, 2, 'trans', '=+AH2+1', []],
      ['AI', 3, 103, 'trans', '=AH4', []],
      ['AJ', 2, 2, 'trans', '=+AI2+1', []],
      ['AJ', 3, 103, 'trans', '=AI4', []],
      ['AK', 2, 2, 'trans', '=+AJ2+1', []],
      ['AK', 3, 103, 'trans', '=AJ4', []],
      ['AL', 2, 2, 'trans', '=+AK2+1', []],
      ['AL', 3, 103, 'trans', '=AK4', []],
      ['AM', 2, 2, 'trans', '=+AL2+1', []],
      ['AM', 3, 103, 'trans', '=AL4', []],
      ['AN', 2, 2, 'trans', '=+AM2+1', []],
      ['AN', 3, 103, 'trans', '=AM4', []],
      ['AO', 2, 2, 'trans', '=+AN2+1', []],
      ['AO', 3, 103, 'trans', '=AN4', []],
      ['AP', 2, 2, 'trans', '=+AO2+1', []],
      ['AP', 3, 103, 'trans', '=AO4', []],
      ['AQ', 2, 2, 'trans', '=+AP2+1', []],
      ['AQ', 3, 103, 'trans', '=AP4', []],
      ['AR', 2, 2, 'trans', '=+AQ2+1', []],
      ['AR', 3, 103, 'trans', '=AQ4', []],
      ['AS', 2, 2, 'trans', '=+AR2+1', []],
      ['AS', 3, 103, 'trans', '=AR4', []],
      ['AT', 2, 2, 'trans', '=+AS2+1', []],
      ['AT', 3, 103, 'trans', '=AS4', []],
      ['AU', 2, 2, 'trans', '=+AT2+1', []],
      ['AU', 3, 103, 'trans', '=AT4', []],
      ['AV', 2, 2, 'trans', '=+AU2+1', []],
      ['AV', 3, 103, 'trans', '=AU4', []],
      ['AW', 2, 2, 'trans', '=+AV2+1', []],
      ['AW', 3, 103, 'trans', '=AV4', []],
      ['AX', 2, 2, 'trans', '=+AW2+1', []],
      ['AX', 3, 103, 'trans', '=AW4', []],
      ['AY', 2, 2, 'trans', '=+AX2+1', []],
      ['AY', 3, 103, 'trans', '=AX4', []],
      ['AZ', 2, 2, 'trans', '=+AY2+1', []],
      ['AZ', 3, 103, 'trans', '=AY4', []],
      ['BA', 2, 2, 'trans', '=+AZ2+1', []],
      ['BA', 3, 103, 'trans', '=AZ4', []],
      ['BB', 2, 2, 'trans', '=+BA2+1', []],
      ['BB', 3, 103, 'trans', '=BA4', []],
      ['BC', 2, 2, 'trans', '=+BB2+1', []],
      ['BC', 3, 103, 'trans', '=BB4', []],
      ['BD', 2, 2, 'trans', '=+BC2+1', []],
      ['BD', 3, 103, 'trans', '=BC4', []],
      ['BE', 2, 2, 'trans', '=+BD2+1', []],
      ['BE', 3, 103, 'trans', '=BD4', []],
      ['BF', 2, 2, 'trans', '=+BE2+1', []],
      ['BF', 3, 103, 'trans', '=BE4', []],
      ['BG', 2, 2, 'trans', '=+BF2+1', []],
      ['BG', 3, 103, 'trans', '=BF4', []],
      ['BH', 2, 2, 'trans', '=+BG2+1', []],
      ['BH', 3, 103, 'trans', '=BG4', []],
      ['BI', 2, 2, 'trans', '=+BH2+1', []],
      ['BI', 3, 103, 'trans', '=BH4', []],
      ['BJ', 2, 2, 'trans', '=+BI2+1', []],
      ['BJ', 3, 103, 'trans', '=BI4', []],
      ['BK', 2, 2, 'trans', '=+BJ2+1', []],
      ['BK', 3, 103, 'trans', '=BJ4', []],
      ['BL', 2, 2, 'trans', '=+BK2+1', []],
      ['BL', 3, 103, 'trans', '=BK4', []],
      ['BM', 2, 2, 'trans', '=+BL2+1', []],
      ['BM', 3, 103, 'trans', '=BL4', []],
      ['BN', 2, 2, 'trans', '=+BM2+1', []],
      ['BN', 3, 103, 'trans', '=BM4', []],
      ['BO', 2, 2, 'trans', '=+BN2+1', []],
      ['BO', 3, 103, 'trans', '=BN4', []],
      ['BP', 2, 2, 'trans', '=+BO2+1', []],
      ['BP', 3, 103, 'trans', '=BO4', []],
      ['BQ', 2, 2, 'trans', '=+BP2+1', []],
      ['BQ', 3, 103, 'trans', '=BP4', []],
      ['BR', 2, 2, 'trans', '=+BQ2+1', []],
      ['BR', 3, 103, 'trans', '=BQ4', []],
      ['BS', 2, 2, 'trans', '=+BR2+1', []],
      ['BS', 3, 103, 'trans', '=BR4', []],
      ['BT', 2, 2, 'trans', '=+BS2+1', []],
      ['BT', 3, 103, 'trans', '=BS4', []],
      ['BU', 2, 2, 'trans', '=+BT2+1', []],
      ['BU', 3, 103, 'trans', '=BT4', []],
      ['BV', 2, 2, 'trans', '=+BU2+1', []],
      ['BV', 3, 103, 'trans', '=BU4', []],
      ['BW', 2, 2, 'trans', '=+BV2+1', []],
      ['BW', 3, 103, 'trans', '=BV4', []],
      ['BX', 2, 2, 'trans', '=+BW2+1', []],
      ['BX', 3, 103, 'trans', '=BW4', []],
      ['BY', 2, 2, 'trans', '=+BX2+1', []],
      ['BY', 3, 103, 'trans', '=BX4', []],
      ['BZ', 2, 2, 'trans', '=+BY2+1', []],
      ['BZ', 3, 103, 'trans', '=BY4', []],
      ['CA', 2, 2, 'trans', '=+BZ2+1', []],
      ['CA', 3, 103, 'trans', '=BZ4', []],
      ['CB', 2, 2, 'trans', '=+CA2+1', []],
      ['CB', 3, 103, 'trans', '=CA4', []],
      ['CC', 2, 2, 'trans', '=+CB2+1', []],
      ['CC', 3, 103, 'trans', '=CB4', []],
      ['CD', 2, 2, 'trans', '=+CC2+1', []],
      ['CD', 3, 103, 'trans', '=CC4', []],
      ['CE', 2, 2, 'trans', '=+CD2+1', []],
      ['CE', 3, 103, 'trans', '=CD4', []],
      ['CF', 2, 2, 'trans', '=+CE2+1', []],
      ['CF', 3, 103, 'trans', '=CE4', []],
      ['CG', 2, 2, 'trans', '=+CF2+1', []],
      ['CG', 3, 103, 'trans', '=CF4', []],
      ['CH', 2, 2, 'trans', '=+CG2+1', []],
      ['CH', 3, 103, 'trans', '=CG4', []],
      ['CI', 2, 2, 'trans', '=+CH2+1', []],
      ['CI', 3, 103, 'trans', '=CH4', []],
      ['CJ', 2, 2, 'trans', '=+CI2+1', []],
      ['CJ', 3, 103, 'trans', '=CI4', []],
      ['CK', 2, 2, 'trans', '=+CJ2+1', []],
      ['CK', 3, 103, 'trans', '=CJ4', []],
      ['CL', 2, 2, 'trans', '=+CK2+1', []],
      ['CL', 3, 103, 'trans', '=CK4', []],
      ['CM', 2, 2, 'trans', '=+CL2+1', []],
      ['CM', 3, 103, 'trans', '=CL4', []],
      ['CN', 2, 2, 'trans', '=+CM2+1', []],
      ['CN', 3, 103, 'trans', '=CM4', []],
      ['CO', 2, 2, 'trans', '=+CN2+1', []],
      ['CO', 3, 103, 'trans', '=CN4', []],
      ['CP', 2, 2, 'trans', '=+CO2+1', []],
      ['CP', 3, 103, 'trans', '=CO4', []],
      ['CQ', 2, 2, 'trans', '=+CP2+1', []],
      ['CQ', 3, 103, 'trans', '=CP4', []],
      ['CR', 2, 2, 'trans', '=+CQ2+1', []],
      ['CR', 3, 103, 'trans', '=CQ4', []],
      ['CS', 2, 2, 'trans', '=+CR2+1', []],
      ['CS', 3, 103, 'trans', '=CR4', []],
      ['CT', 2, 2, 'trans', '=+CS2+1', []],
      ['CT', 3, 103, 'trans', '=CS4', []],
      ['CU', 2, 2, 'trans', '=+CT2+1', []],
      ['CU', 3, 103, 'trans', '=CT4', []],
      ['CV', 2, 2, 'trans', '=+CU2+1', []],
      ['CV', 3, 103, 'trans', '=CU4', []],
      ['CW', 2, 2, 'trans', '=+CV2+1', []],
      ['CW', 3, 103, 'trans', '=CV4', []],
      ['CX', 2, 2, 'trans', '=+CW2+1', []],
      ['CX', 3, 103, 'trans', '=CW4', []],
    ],
    "colfmt": {
        'B': '0.0%',
        'C': '0.0%',
        'D': '0.0%',
        'E': '0.0%',
        'F': '0.0%',
        'G': '0.0%',
        'H': '0.0%',
        'I': '0.0%',
        'J': '0.0%',
        'K': '0.0%',
        'L': '0.0%',
        'M': '0.0%',
        'N': '0.0%',
        'O': '0.0%',
        'P': '0.0%',
        'Q': '0.0%',
        'R': '0.0%',
        'S': '0.0%',
        'T': '0.0%',
        'U': '0.0%',
        'V': '0.0%',
        'W': '0.0%',
        'X': '0.0%',
        'Y': '0.0%',
        'Z': '0.0%',
        'AA': '0.0%',
        'AB': '0.0%',
        'AC': '0.0%',
        'AD': '0.0%',
        'AE': '0.0%',
        'AF': '0.0%',
        'AG': '0.0%',
        'AH': '0.0%',
        'AI': '0.0%',
        'AJ': '0.0%',
        'AK': '0.0%',
        'AL': '0.0%',
        'AM': '0.0%',
        'AN': '0.0%',
        'AO': '0.0%',
        'AP': '0.0%',
        'AQ': '0.0%',
        'AR': '0.0%',
        'AS': '0.0%',
        'AT': '0.0%',
        'AU': '0.0%',
        'AV': '0.0%',
        'AW': '0.0%',
        'AX': '0.0%',
        'AY': '0.0%',
        'AZ': '0.0%',
        'BA': '0.0%',
        'BB': '0.0%',
        'BC': '0.0%',
        'BD': '0.0%',
        'BE': '0.0%',
        'BF': '0.0%',
        'BG': '0.0%',
        'BH': '0.0%',
        'BI': '0.0%',
        'BJ': '0.0%',
        'BK': '0.0%',
        'BL': '0.0%',
        'BM': '0.0%',
        'BN': '0.0%',
        'BO': '0.0%',
        'BP': '0.0%',
        'BQ': '0.0%',
        'BR': '0.0%',
        'BS': '0.0%',
        'BT': '0.0%',
        'BU': '0.0%',
        'BV': '0.0%',
        'BW': '0.0%',
        'BX': '0.0%',
        'BY': '0.0%',
        'BZ': '0.0%',
        'CA': '0.0%',
        'CB': '0.0%',
        'CC': '0.0%',
        'CD': '0.0%',
        'CE': '0.0%',
        'CF': '0.0%',
        'CG': '0.0%',
        'CH': '0.0%',
        'CI': '0.0%',
        'CJ': '0.0%',
        'CK': '0.0%',
        'CL': '0.0%',
        'CM': '0.0%',
        'CN': '0.0%',
        'CO': '0.0%',
        'CP': '0.0%',
        'CQ': '0.0%',
        'CR': '0.0%',
        'CS': '0.0%',
        'CT': '0.0%',
        'CU': '0.0%',
        'CV': '0.0%',
        'CW': '0.0%',
        'CX': '0.0%',
    },
    "fmt_exc": {
        'B1': 'General',
        'B2': 'General',
        'C2': 'General',
        'D2': 'General',
        'E2': 'General',
        'F2': 'General',
        'G2': 'General',
        'H2': 'General',
        'I2': 'General',
        'J2': 'General',
        'K2': 'General',
        'L2': 'General',
        'M2': 'General',
        'N2': 'General',
        'O2': 'General',
        'P2': 'General',
        'Q2': 'General',
        'R2': 'General',
        'S2': 'General',
        'T2': 'General',
        'U2': 'General',
        'V2': 'General',
        'W2': 'General',
        'X2': 'General',
        'Y2': 'General',
        'Z2': 'General',
        'AA2': 'General',
        'AB2': 'General',
        'AC2': 'General',
        'AD2': 'General',
        'AE2': 'General',
        'AF2': 'General',
        'AG2': 'General',
        'AH2': 'General',
        'AI2': 'General',
        'AJ2': 'General',
        'AK2': 'General',
        'AL2': 'General',
        'AM2': 'General',
        'AN2': 'General',
        'AO2': 'General',
        'AP2': 'General',
        'AQ2': 'General',
        'AR2': 'General',
        'AS2': 'General',
        'AT2': 'General',
        'AU2': 'General',
        'AV2': 'General',
        'AW2': 'General',
        'AX2': 'General',
        'AY2': 'General',
        'AZ2': 'General',
        'BA2': 'General',
        'BB2': 'General',
        'BC2': 'General',
        'BD2': 'General',
        'BE2': 'General',
        'BF2': 'General',
        'BG2': 'General',
        'BH2': 'General',
        'BI2': 'General',
        'BJ2': 'General',
        'BK2': 'General',
        'BL2': 'General',
        'BM2': 'General',
        'BN2': 'General',
        'BO2': 'General',
        'BP2': 'General',
        'BQ2': 'General',
        'BR2': 'General',
        'BS2': 'General',
        'BT2': 'General',
        'BU2': 'General',
        'BV2': 'General',
        'BW2': 'General',
        'BX2': 'General',
        'BY2': 'General',
        'BZ2': 'General',
        'CA2': 'General',
        'CB2': 'General',
        'CC2': 'General',
        'CD2': 'General',
        'CE2': 'General',
        'CF2': 'General',
        'CG2': 'General',
        'CH2': 'General',
        'CI2': 'General',
        'CJ2': 'General',
        'CK2': 'General',
        'CL2': 'General',
        'CM2': 'General',
        'CN2': 'General',
        'CO2': 'General',
        'CP2': 'General',
        'CQ2': 'General',
        'CR2': 'General',
        'CS2': 'General',
        'CT2': 'General',
        'CU2': 'General',
        'CV2': 'General',
        'CW2': 'General',
        'CX2': 'General',
    },
    "widths": {},
  },
  'Projection_Monthly': {
    "statics": {
        'A1': 'Plan',
        'B1': 'Date',
        'C1': 'Month Index',
        'D1': 'Duration',
        'E1': 'Attained Age',
        'F1': 'Last Anniv',
        'G1': 'Next Anniv',
        'H1': 'Frac within Year',
        'I1': 'CV Factor_n',
        'J1': 'CV Factor_n+1',
        'K1': 'CV per 1000',
        'L1': 'CV Total (Base)',
        'M1': 'PUA CV',
        'N1': 'Pre-Dividend PUA SA (cum)',
        'O1': 'Dividend Base SA',
        'P1': 'Monthly Div Rate',
        'Q1': 'Dividend Amount',
        'R1': 'Accum Div ',
        'S1': 'Accum Div Prev End',
        'T1': 'Accum Div Prev Growth',
        'U1': 'Out-of-Pocket Premium',
        'V1': 'Cash Dividend Paid',
        'W1': 'Dividend to PUA',
        'X1': 'PUA SP per $1 SA',
        'Y1': 'PUA SA Add (this month)',
        'Z1': 'PUA SA (cum)',
        'AA1': 'CV from PUA',
        'AB1': 'CV Total (Incl PUA)',
        'AC1': 'Premium Offset Applied (Div + Accum Div growth)',
    },
    "arrays": [],
    "fills": [
      ['A', 2, 2, 'trans', '=IF(Inputs!$B$7>MAX(MORTALITY!$A:$A),"",Inputs!$B$4)', []],
      ['A', 3, 1050, 'trans', '=IF(A2="","",IF(INT((C2+1)/12)+Inputs!$B$7>MAX(MORTALITY!$A:$A),"",Inputs!$B$4))', []],
      ['B', 2, 2, 'trans', '=IF(A2="","",Inputs!$B$11)', []],
      ['B', 3, 1050, 'trans', '=IF(A3="","",EOMONTH(B2,1))', []],
      ['C', 2, 2, 'trans', '=IF(A2="","",0)', []],
      ['C', 3, 1050, 'trans', '=IF(A3="","",C2+1)', []],
      ['D', 2, 1050, 'trans', '=IF(A2="","",INT(C2/12))', []],
      ['E', 2, 1050, 'trans', '=IF(A2="","",D2+Inputs!$B$7)', []],
      ['F', 2, 1050, 'trans', '=IF(A2="","",DATE(YEAR(B$2)+D2,MONTH(B$2),DAY(B$2)))', []],
      ['G', 2, 1050, 'trans', '=IF(A2="","",DATE(YEAR(F2)+1,MONTH(F2),DAY(F2)))', []],
      ['H', 2, 1050, 'trans', '=IF(A2="","",IF(G2>F2,(B2-F2)/(G2-F2),0))', []],
      ['I', 2, 1050, 'trans', '=IF(A2="","",IFERROR(INDEX(CV_RATES!$I:$I,MATCH(D2,CV_RATES!$C:$C,0)),0))', []],
      ['J', 2, 1050, 'trans', '=IF(A2="","",IFERROR(IF(E2=MAX(MORTALITY!$A:$A),1000,INDEX(CV_RATES!$J:$J,MATCH(D2,CV_RATES!$C:$C,0))),0))', []],
      ['K', 2, 1050, 'trans', '=IF(A2="","",IFERROR(I2+H2*(J2-I2),0))', []],
      ['L', 2, 1050, 'trans', '=IF(A2="","",IFERROR(K2*Inputs!$B$9,0))', []],
      ['M', 2, 1050, 'trans', '=IF(A2="","",IFERROR(K2*Inputs!$B$10,0))', []],
      ['N', 2, 2, 'trans', '=IF(A2="","",0)', []],
      ['N', 3, 1050, 'trans', '=IF(A3="","",Z2)', []],
      ['O', 2, 1050, 'trans', '=IF(A2="","",Inputs!$B$18+N2)', []],
      ['P', 2, 1050, 'trans', '=IF(A2="","",VLOOKUP(D2,DIvidend_Assumption!$A$3:$CX$103,($E$2+2),0)/12)', []],
      ['Q', 2, 2, 'trans', '=IF(A2="","",0)', []],
      ['Q', 3, 1050, 'trans', '=IF(A3="","",IFERROR(AB2*P3,""))', []],
      ['R', 2, 1050, 'trans', '=IF(A2="","",IFERROR(IF(Inputs!$B$22="Accumulate",T2+Q2,IF(Inputs!$B$22="Premium Offset",MAX(0,T2+Q2-Inputs!$B$25),T2)),""))', []],
      ['S', 2, 2, 'trans', '=IF(A2="","",0)', []],
      ['S', 3, 1050, 'trans', '=IF(A3="","",R2)', []],
      ['T', 2, 1050, 'trans', '=IF(A2="","",IFERROR(S2*(1+Inputs!$B$23/12),""))', []],
      ['U', 2, 1050, 'trans', '=IF(A2="","",IF(D2<=Inputs!$B$8,IF(Inputs!$B$22="Premium Offset",MAX(0,Inputs!$B$25-(Q2+T2)),Inputs!$B$25),0))', []],
      ['V', 2, 1050, 'trans', '=IF(A2="","",IF(Inputs!$B$22="Cash",Q2,0))', []],
      ['W', 2, 1050, 'trans', '=IF(A2="","",IF(Inputs!$B$22="PUA",Q2,0))', []],
      ['X', 2, 1050, 'trans', '=IF(A2="","",IFERROR(INDEX(PUA_TABLE!$D$4:$D$105,MATCH(E2,PUA_TABLE!$C$4:$C$105,1)),0))', []],
      ['Y', 2, 1050, 'trans', '=IF(A2="","",IF(W2>0,IF(X2>0,W2/X2,0),0))', []],
      ['Z', 2, 1050, 'trans', '=IF(A2="","",N2+Y2)', []],
      ['AA', 2, 2, 'trans', '=IF(A2="","",IFERROR(W2,0))', []],
      ['AA', 3, 1050, 'trans', '=IF(A3="","",IFERROR(Z3*INDEX(PUA_TABLE!$I$4:$I$105,MATCH(E3,PUA_TABLE!$C$4:$C$105,1))/1000,0))', []],
      ['AB', 2, 1050, 'trans', '=IF(A2="","",IFERROR(L2+AA2,0))', []],
      ['AC', 2, 1050, 'trans', '=IF(A2="","",IF(Inputs!$B$22="Premium Offset",MIN(Inputs!$B$25,Q2+T2),0))', []],
    ],
    "colfmt": {
        'B': 'mm-dd-yy',
        'F': 'mm-dd-yy',
        'G': 'mm-dd-yy',
        'H': '0.00',
        'I': '0.00',
        'J': '0.00',
        'K': '0.00',
        'L': '0.00',
        'M': '0.00',
        'N': '0.00',
        'O': '0',
        'P': '0.00%',
        'Q': '0.00',
        'R': '0.00',
        'S': '0.00',
        'T': '0.00',
        'U': '0',
        'V': '0.00',
        'W': '0.00',
        'X': '0.000',
        'Y': '0.00',
        'Z': '0.00',
        'AA': '0.00',
        'AB': '0.00',
        'AC': '0.00',
    },
    "fmt_exc": {
        'B1': 'General',
        'H1': 'General',
        'I1': 'General',
        'J1': 'General',
        'K1': 'General',
        'L1': 'General',
        'M1': 'General',
        'N1': 'General',
        'O1': 'General',
        'Q1': 'General',
        'R1': 'General',
        'S1': 'General',
        'T1': 'General',
        'U1': 'General',
        'V1': 'General',
        'W1': 'General',
        'X1': 'General',
        'Y1': 'General',
        'Z1': 'General',
        'AA1': 'General',
        'AB1': 'General',
        'AC1': 'General',
    },
    "widths": {'B': 11.0, 'C': 13.82, 'D': 10.45, 'E': 13.73, 'F': 11.54, 'G': 12.18, 'H': 16.45, 'I': 13.45, 'J': 15.0, 'K': 13.0, 'L': 15.54, 'N': 25.82, 'O': 17.45, 'P': 17.45, 'Q': 17.73, 'R': 12.18, 'S': 19.54, 'T': 22.73, 'U': 22.82, 'V': 19.0, 'W': 16.54, 'X': 17.27, 'Y': 23.82, 'Z': 14.45, 'AA': 13.73, 'AB': 18.54, 'AC': 45.0},
  },
  'RPU': {
    "statics": {
        'A1': 'Reduced Paid-Up (RPU) - Actuarial Calculation',
        'A3': 'Status',
        'A4': 'Attained Age',
        'A5': 'Original Sum Assured',
        'A7': '═══ Method 1: Cash Value / Net Single Premium ═══',
        'A8': 'Gross Cash Value (tVx)',
        'A9': 'Net Single Premium at Attained Age (Ax)',
        'A10': 'RPU SA (Uncapped) = CV / Ax',
        'A12': '═══ Method 2: Reserve Ratio (Actuarial Formula) ═══',
        'A13': 'Reserve per $1000 at Duration t',
        'A14': 'RPU SA = SA × (tVx/1000) / Ax',
        'A16': '═══════════════════════════════════════════════',
        'A17': 'FINAL RPU Sum Assured',
        'A19': 'Comparison:',
        'A20': 'Is Capping Applied?',
        'A22': 'Note: When CV/Ax > SA, capping prevents over-insurance.',
        'A23': 'Both methods should yield the same result when using',
        'A24': 'consistent actuarial assumptions.',
    },
    "arrays": [],
    "fills": [
      ['B', 3, 3, 'trans', '=IF(Inputs!$B$30=FALSE,"N/A - Policy is already Paid-Up (beyond PPT)","Applicable")', []],
      ['B', 4, 4, 'trans', '=IF(Inputs!$B$30=FALSE,"",Inputs!$B$15)', []],
      ['B', 5, 5, 'trans', '=IF(Inputs!$B$30=FALSE,"",Inputs!$B$18)', []],
      ['B', 8, 8, 'trans', '=IF(Inputs!$B$30=FALSE,"",INDEX(CV_RATES!$J:$J,MATCH(Inputs!$B$16,CV_RATES!$C:$C,0))/1000*Inputs!$B$18)', []],
      ['B', 9, 9, 'trans', '=IF(Inputs!$B$30=FALSE,"",INDEX(Commutation!$K:$K,MATCH(Inputs!$B$15,Commutation!$A:$A,0)))', []],
      ['B', 10, 10, 'trans', '=IF(Inputs!$B$30=FALSE,"",IFERROR(B8/B9,""))', []],
      ['B', 13, 13, 'trans', '=IF(Inputs!$B$30=FALSE,"",INDEX(CV_RATES!$J:$J,MATCH(Inputs!$B$16,CV_RATES!$C:$C,0)))', []],
      ['B', 14, 14, 'trans', '=IF(Inputs!$B$30=FALSE,"",IFERROR(B5*(B13/1000)/B9,""))', []],
      ['B', 17, 17, 'trans', '=IF(Inputs!$B$30=FALSE,"",MIN(B10,B5))', []],
      ['B', 20, 20, 'trans', '=IF(Inputs!$B$30=FALSE,"",IF(B10>B5,"YES - Calculated RPU exceeds Original SA","NO - Within limits"))', []],
    ],
    "colfmt": {},
    "fmt_exc": {},
    "widths": {'A': 63.54, 'B': 27.27, 'D': 32.0, 'E': 22.0},
  },
  'ETI': {
    "statics": {
        'A1': 'Extended Term Insurance (ETI) - Calculations',
        'D2': 'Status',
        'A3': 'Discount Rate',
        'D3': 'ETI Years (full)',
        'A4': 'Face Amount',
        'D4': 'Partial Year (fraction)',
        'A5': 'Gross Cash Value',
        'D5': 'ETI Duration (years)',
        'A6': 'Attained Age at Val Date',
        'D6': 'ETI Expiry Date',
        'A7': 'v (1/(1+i))',
        'A8': 'Policy Year of ETI',
        'B8': 'Age',
        'C8': 'Term Cost per $1 SA for 1 Year',
        'D8': 'Cash Value required for Base face Amt for 1 Year',
        'E8': 'Remaining CV after cumulative ETI cost',
        'F8': 'Indicator',
    },
    "arrays": ['E3', 'E4'],
    "fills": [
      ['A', 9, 9, 'trans', '=IF(Inputs!$B$30=FALSE,"",IF($B$6>MAX(MORTALITY!$A:$A),"",1))', []],
      ['A', 10, 51, 'trans', '=IF(OR(A9="",B9>=MAX(MORTALITY!$A:$A)),"",A9+1)', []],
      ['B', 3, 3, 'trans', '=Inputs!$B$23', []],
      ['B', 4, 4, 'trans', '=IF(Inputs!$B$30=FALSE,"",Inputs!$B$18)', []],
      ['B', 5, 5, 'trans', '=Inputs!$E$2', []],
      ['B', 6, 6, 'trans', '=IF(Inputs!$B$30=FALSE,"",Inputs!B15)', []],
      ['B', 7, 7, 'trans', '=1/(1+B3)', []],
      ['B', 9, 9, 'trans', '=B6', []],
      ['B', 10, 51, 'trans', '=IF(OR(B9="",B9>=MAX(MORTALITY!$A:$A)),"",B9+1)', []],
      ['C', 9, 51, 'trans', '=IF(A9="","",IFERROR(INDEX(MORTALITY!$D:$D,MATCH(B9,MORTALITY!$A:$A,0)),""))', []],
      ['D', 9, 51, 'trans', '=IF(A9="","",IFERROR(C9*$B$4,""))', []],
      ['E', 2, 2, 'trans', '=IF(Inputs!$B$30=FALSE,"N/A - Policy is already Paid-Up (beyond PPT)","Applicable")', []],
      ['E', 3, 3, 'lit', '=IF(Inputs!$B$30=FALSE,"",IFERROR(MATCH(TRUE,E9:E51<0,0)-1,SUMPRODUCT((E9:E51<>"")*1)))', []],
      ['E', 4, 4, 'lit', '=IF(Inputs!$B$30=FALSE,"",IFERROR(IF(E3="","",IF(INDEX(E9:E51,E3+1)<0,INDEX(E9:E51,E3)/(INDEX(E9:E51,E3)-INDEX(E9:E51,E3+1)),0)),""))', []],
      ['E', 5, 5, 'trans', '=IF(Inputs!$B$30=FALSE,"",IFERROR(IF(OR(E3="",E4=""),"",E3+E4),""))', []],
      ['E', 6, 6, 'trans', '=IF(Inputs!$B$30=FALSE,"",IFERROR(IF(E5="","",Inputs!B12+365*E5),""))', []],
      ['E', 9, 9, 'trans', '=IF(A9="","",IFERROR($B$5-SUM($D$9),""))', []],
      ['E', 10, 51, 'trans', '=IF(A10="","",IFERROR($B$5-SUM($D$9:D10),""))', []],
      ['F', 9, 50, 'trans', '=IF(A9="","",IF(AND(E10<0,E9>0),1,0))', []],
      ['F', 51, 51, 'trans', '=IF(A51="","",0)', []],
    ],
    "colfmt": {
        'D': '0.00',
        'E': '0.00',
        'C': '0.000000',
    },
    "fmt_exc": {
        'D2': 'General',
        'E2': 'General',
        'B3': '0.00%',
        'D3': 'General',
        'E3': 'General',
        'D4': 'General',
        'E4': '0.00%',
        'B5': '0',
        'D5': 'General',
        'D6': 'General',
        'E6': 'mm-dd-yy',
        'B7': '0.0000000',
        'C8': 'General',
        'D8': 'General',
        'E8': 'General',
    },
    "widths": {'A': 23.18, 'B': 20.0, 'C': 17.73, 'D': 23.18, 'E': 19.54, 'F': 12.27},
  },
  'APL': {
    "statics": {
        'A1': 'Automatic Premium Loan (APL)',
        'A3': 'APL Enabled (TRUE/FALSE)',
        'D3': 'Legend',
        'F3': 'Link with Data/Input',
        'A4': 'Policy Loan Interest Rate (p.a.)',
        'B4': 0.08,
        'F4': 'Formulae',
        'A5': 'Payments per Year (mode)',
        'F5': 'Dropdown Selection',
        'A6': 'Valuation Date',
        'A7': 'Annual Premium',
        'A8': 'Modal Premium',
        'E8': 'Status',
        'A9': 'CV at Valuation Date',
        'E9': 'Policy End Date',
        'A10': 'Loanable % of CV',
        'B10': 0.8,
        'E10': 'APL End Date',
        'A11': 'Premium Paying Term (PPT)',
        'A13': 'Period #',
        'B13': 'Due Date (approx)',
        'C13': 'Beginning Balance',
        'D13': 'Interest',
        'E13': 'APL Drawn',
        'F13': 'Payment Covered by APL',
        'G13': 'Ending Balance',
        'H13': 'Net CV (CV - Loan)',
        'I13': 'Policy Status',
        'J13': 'Indicator',
    },
    "arrays": [],
    "fills": [
      ['A', 14, 14, 'trans', '=IF(Inputs!$B$30=FALSE,"",1)', []],
      ['A', 15, 199, 'trans', '=IF(OR(A14="",H14<=0),"",A14+1)', []],
      ['B', 3, 3, 'trans', '=TRUE()', []],
      ['B', 5, 5, 'trans', '=Inputs!$B$27', []],
      ['B', 6, 6, 'trans', '=Inputs!$B$12', []],
      ['B', 7, 7, 'trans', '=IF(Inputs!$B$30=FALSE,"",IFERROR(INDEX(Inputs!B:B,MATCH("Annual Base Premium",Inputs!A:A,0)),0))', []],
      ['B', 8, 8, 'trans', '=IF(Inputs!$B$30=FALSE,"",IFERROR(INDEX(Inputs!B:B,MATCH("Modal Premium",Inputs!A:A,0)),IF(B7>0,B7/B5,0)))', []],
      ['B', 9, 9, 'trans', '=Inputs!$E$2', []],
      ['B', 11, 11, 'trans', '=Inputs!$B$8', []],
      ['B', 14, 14, 'trans', '=IF(Inputs!$B$30=FALSE,"",B6)', []],
      ['B', 15, 199, 'trans', '=IF(A15="","",EOMONTH(B14,12/$B$5))', []],
      ['C', 14, 14, 'trans', '=IF(Inputs!$B$30=FALSE,"",0)', []],
      ['C', 15, 199, 'trans', '=IF(A15="","",G14)', []],
      ['D', 14, 14, 'trans', '=IF(Inputs!$B$30=FALSE,"",C14*$B$4/$B$5)', []],
      ['D', 15, 199, 'trans', '=IF(A15="","",C15*$B$4/$B$5)', []],
      ['E', 14, 14, 'trans', '=IF(Inputs!$B$30=FALSE,"",IF(AND(B14<=$F$9,$B$8+C14+D14<$B$9*$B$10),$B$8,0))', []],
      ['E', 15, 199, 'trans', '=IF(A15="","",IF(AND(B15<=$F$9,C15+D15+$B$8<VLOOKUP(B15,Projection_Monthly!$B:$AB,26,TRUE)*$B$10),$B$8,0))', []],
      ['F', 8, 8, 'trans', '=IF(Inputs!$B$30=FALSE,"N/A - Policy is already Paid-Up (beyond PPT)","Applicable")', []],
      ['F', 9, 9, 'trans', '=EDATE(Inputs!$B$11,Inputs!$B$8*12)', []],
      ['F', 10, 10, 'trans', '=IFERROR(_xlfn.XLOOKUP(1,J14:J199,B14:B199),"")', []],
      ['F', 14, 14, 'trans', '=IF(Inputs!$B$30=FALSE,"",MIN($B$8,E14))', []],
      ['F', 15, 199, 'trans', '=IF(A15="","",MIN($B$8,E15))', []],
      ['G', 14, 14, 'trans', '=IF(Inputs!$B$30=FALSE,"",C14+D14+E14)', []],
      ['G', 15, 199, 'trans', '=IF(A15="","",C15+D15+E15)', []],
      ['H', 14, 199, 'trans', '=IF(A14="","",IF(Inputs!$B$30=FALSE,"",$B$9-G14))', []],
      ['I', 14, 14, 'trans', '=IF(Inputs!$B$30=FALSE,"",IF(H14>0,"Active","LAPSED"))', []],
      ['I', 15, 199, 'trans', '=IF(A15="","",IF(H15>0,"Active","LAPSED"))', []],
      ['J', 14, 199, 'trans', '=IF(A14="","",IF(AND(H15<0,H14>0),1,0))', []],
    ],
    "colfmt": {
        'B': 'mm-dd-yy',
        'D': '0',
        'E': '0',
        'C': '0',
        'G': '0',
        'H': '0',
    },
    "fmt_exc": {
        'B3': 'General',
        'D3': 'General',
        'B4': '0%',
        'B5': 'General',
        'B7': '0',
        'B8': '0',
        'E8': 'General',
        'B9': '0',
        'E9': 'General',
        'F9': 'mm-dd-yy',
        'B10': '0%',
        'E10': 'General',
        'F10': 'mm-dd-yy',
        'B11': '0',
        'B13': 'General',
        'C13': 'General',
        'D13': 'General',
        'E13': 'General',
        'G13': 'General',
        'H13': 'General',
    },
    "widths": {'A': 27.27, 'B': 16.45, 'C': 15.82, 'D': 7.45, 'E': 13.82, 'F': 21.82, 'G': 20.18, 'H': 28.18, 'I': 11.36, 'L': 9.45},
  },
  'Loan': {
    "statics": {
        'A1': 'LOAN MODULE - Multiple Loans & Repayments',
        'S1': 'HELPER COLUMNS (can be hidden)',
        'W1': 'SORTED EVENTS',
        'S2': 'Date',
        'T2': 'Type',
        'U2': 'Amount',
        'V2': 'Sort Key',
        'W2': '#',
        'X2': 'Date',
        'Y2': 'Type',
        'Z2': 'Amount',
        'A3': 'Input Parameters',
        'W3': 1,
        'A4': 'Loan Interest Rate',
        'W4': 2,
        'A5': 'Guaranteed Interest Rate',
        'W5': 3,
        'A6': 'Issue Age',
        'W6': 4,
        'A7': 'Issue Date',
        'W7': 5,
        'A8': 'Valuation Date',
        'W8': 6,
        'A9': 'Face Amount (SA)',
        'W9': 7,
        'A10': 'Premium Paying Term (PPT)',
        'W11': 8,
        'A12': 'LOAN TRANSACTIONS (Enter up to 10 loans)',
        'E12': 'REPAYMENT TRANSACTIONS (Enter up to 10 repayments)',
        'W12': 9,
        'A13': 'Loan #',
        'B13': 'Loan Date',
        'C13': 'Loan Amount',
        'E13': 'Repay #',
        'F13': 'Repayment Date',
        'G13': 'Repayment Amount',
        'W13': 10,
        'A14': 1,
        'C14': 500,
        'E14': 1,
        'F14': ['__dt__', '2025-03-01T00:00:00'],
        'G14': 20,
        'W14': 11,
        'A15': 2,
        'B15': ['__dt__', '2024-10-14T00:00:00'],
        'C15': 0,
        'E15': 2,
        'W15': 12,
        'A16': 3,
        'B16': ['__dt__', '2025-10-14T00:00:00'],
        'C16': 20,
        'E16': 3,
        'W16': 13,
        'A17': 4,
        'B17': ['__dt__', '2025-10-31T00:00:00'],
        'C17': 0,
        'E17': 4,
        'W17': 14,
        'A18': 5,
        'E18': 5,
        'W18': 15,
        'A19': 6,
        'E19': 6,
        'W19': 16,
        'A20': 7,
        'E20': 7,
        'W20': 17,
        'A21': 8,
        'E21': 8,
        'W21': 18,
        'A22': 9,
        'E22': 9,
        'W22': 19,
        'A23': 10,
        'C23': 0,
        'E23': 10,
        'W23': 20,
        'W24': 21,
        'W25': 22,
        'A26': 'ADVANCE METHOD (Compound Interest - Interest charged at beginning of period)',
        'J26': 'ARREAR METHOD (Compound Interest - Interest charged at end of period)',
        'W26': 23,
        'A27': 'Event #',
        'B27': 'Date',
        'C27': 'Type',
        'D27': 'Amount',
        'E27': 'Days from Prior',
        'F27': 'Interest Accrued',
        'G27': 'Outstanding After',
        'H27': 'Is Anniversary?',
        'J27': 'Event #',
        'K27': 'Date',
        'L27': 'Type',
        'M27': 'Amount',
        'N27': 'Days from Prior',
        'O27': 'Interest Accrued',
        'P27': 'Outstanding After',
        'Q27': 'Is Anniversary?',
        'W27': 24,
        'W28': 25,
        'W29': 26,
        'W30': 27,
        'W31': 28,
        'W32': 29,
        'W33': 30,
        'W34': 31,
        'W35': 32,
        'W36': 33,
        'W37': 34,
        'W38': 35,
        'W39': 36,
        'W40': 37,
        'A41': 'NOTES:',
        'A42': '1. ADVANCE METHOD: Interest is charged at the beginning of each period (prepaid interest).',
        'A43': '2. ARREAR METHOD: Interest is charged at the end of each period (accrued interest).',
        'A44': '3. Both methods use the formula: Interest = Principal × ((1 + Rate)^(Days/365) - 1)',
        'A45': '4. Outstanding balance shown is the amount owed after each transaction/event.',
        'A46': '5. Loan interest is charged daily and compounded at each anniversary or event.',
        'A47': "6. Maximum loan amount typically cannot exceed the policy's cash value.",
        'A48': '7. Anniversaries are automatically calculated from Issue Date for periods between first loan and Valuation Date.',
    },
    "arrays": ['X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'X9', 'X11', 'X12', 'X13', 'X14', 'X15', 'X16', 'X17', 'X18', 'X19', 'X20', 'X21', 'X22', 'X23', 'X24', 'X25', 'X26', 'X27', 'X28', 'X29', 'X30', 'X31', 'X32', 'X33', 'X34', 'X35', 'X36', 'X37', 'X38', 'X39', 'X40'],
    "fills": [
      ['A', 28, 34, 'trans', '=IF(X3="","",W3)', []],
      ['A', 35, 40, 'trans', '=IF(X11="","",W11)', []],
      ['B', 4, 4, 'trans', '=Inputs!$B$31', []],
      ['B', 5, 5, 'trans', '=Inputs!$B$23', []],
      ['B', 6, 6, 'trans', '=Inputs!$B$7', []],
      ['B', 7, 7, 'trans', '=Inputs!$B$11', []],
      ['B', 8, 8, 'trans', '=Inputs!$B$12', []],
      ['B', 9, 9, 'trans', '=Inputs!$B$18', []],
      ['B', 10, 10, 'trans', '=Inputs!$B$8', []],
      ['B', 14, 14, 'trans', '=Inputs!$B$33', []],
      ['B', 23, 23, 'trans', '=B8', []],
      ['B', 28, 34, 'trans', '=IF(X3="","",X3)', []],
      ['B', 35, 40, 'trans', '=IF(X11="","",X11)', []],
      ['C', 28, 34, 'trans', '=IF(X3="","",Y3)', []],
      ['C', 35, 40, 'trans', '=IF(X11="","",Y11)', []],
      ['D', 28, 34, 'trans', '=IF(X3="","",Z3)', []],
      ['D', 35, 40, 'trans', '=IF(X11="","",Z11)', []],
      ['E', 28, 28, 'trans', '=IF(B28="","",0)', []],
      ['E', 29, 40, 'trans', '=IF(B29="","",IF(B28="",0,B29-B28))', []],
      ['F', 28, 40, 'trans', '=IF(B28="","",D28*((1+$B$4)^(E28/365)-1))', []],
      ['G', 28, 28, 'trans', '=IF(B28="","",IF(C28="LOAN",D28*(1+$B$4*0),IF(C28="REPAY",-D28,0)))', []],
      ['G', 29, 40, 'trans', '=IF(B29="","",G28*(1+$B$4)^(E29/365)+IF(C29="LOAN",D29*(1+$B$4)^(E29/365),IF(C29="REPAY",-D29,0)))', []],
      ['H', 28, 40, 'trans', '=IF(B28="","",IF(C28="ANNIV","Yes",""))', []],
      ['J', 28, 34, 'trans', '=IF(X3="","",W3)', []],
      ['J', 35, 40, 'trans', '=IF(X11="","",W11)', []],
      ['K', 28, 34, 'trans', '=IF(X3="","",X3)', []],
      ['K', 35, 40, 'trans', '=IF(X11="","",X11)', []],
      ['L', 28, 34, 'trans', '=IF(X3="","",Y3)', []],
      ['L', 35, 40, 'trans', '=IF(X11="","",Y11)', []],
      ['M', 28, 34, 'trans', '=IF(X3="","",Z3)', []],
      ['M', 35, 40, 'trans', '=IF(X11="","",Z11)', []],
      ['N', 28, 28, 'trans', '=IF(K28="","",0)', []],
      ['N', 29, 40, 'trans', '=IF(K29="","",IF(K28="",0,K29-K28))', []],
      ['O', 28, 28, 'trans', '=IF(K28="","",0)', []],
      ['O', 29, 40, 'trans', '=IF(K29="","",IFERROR(P28*((1+$B$4)^(N29/365)-1),0))', []],
      ['P', 28, 28, 'trans', '=IF(K28="","",IF(L28="LOAN",M28,IF(L28="REPAY",-M28,0)))', []],
      ['P', 29, 40, 'trans', '=IF(K29="","",P28+O29+IF(L29="LOAN",M29,IF(L29="REPAY",-M29,0)))', []],
      ['Q', 28, 40, 'trans', '=IF(K28="","",IF(L28="ANNIV","Yes",""))', []],
      ['S', 3, 13, 'trans', '=IF(B14="","",B14)', []],
      ['S', 14, 23, 'trans', '=IF(F14="","",F14)', []],
      ['S', 24, 40, 'counter', '=IFERROR(IF(AND(DATE(YEAR($B$7)+1,MONTH($B$7),DAY($B$7))>_xlfn.MINIFS($B$14:$B$23,$B$14:$B$23,">0"),DATE(YEAR($B$7)+1,MONTH($B$7),DAY($B$7))<=$B$8),DATE(YEAR($B$7)+1,MONTH($B$7),DAY($B$7)),""),"")', [0, 2, 3]],
      ['T', 3, 13, 'trans', '=IF(B14="","",IF(S3=$B$8,"VALUATION","LOAN"))', []],
      ['T', 14, 23, 'trans', '=IF(F14="","","REPAY")', []],
      ['T', 24, 40, 'trans', '=IF(S24="","","ANNIV")', []],
      ['U', 3, 13, 'trans', '=IF(C14="","",C14)', []],
      ['U', 14, 23, 'trans', '=IF(G14="","",G14)', []],
      ['U', 24, 40, 'trans', '=IF(S24="","",0)', []],
      ['V', 3, 13, 'trans', '=IF(B14="","",B14+0.1)', []],
      ['V', 14, 23, 'trans', '=IF(F14="","",F14+0.2)', []],
      ['V', 24, 40, 'trans', '=IF(S24="","",S24)', []],
      ['X', 3, 3, 'lit', '=IFERROR(SMALL(IF($S$3:$S$64<>"",$S$3:$S$64),1),"")', []],
      ['X', 4, 4, 'lit', '=IFERROR(SMALL(IF($S$3:$S$64<>"",$S$3:$S$64),2),"")', []],
      ['X', 5, 5, 'lit', '=IFERROR(SMALL(IF($S$3:$S$64<>"",$S$3:$S$64),3),"")', []],
      ['X', 6, 6, 'lit', '=IFERROR(SMALL(IF($S$3:$S$64<>"",$S$3:$S$64),4),"")', []],
      ['X', 7, 7, 'lit', '=IFERROR(SMALL(IF($S$3:$S$64<>"",$S$3:$S$64),5),"")', []],
      ['X', 8, 8, 'lit', '=IFERROR(SMALL(IF($S$3:$S$64<>"",$S$3:$S$64),6),"")', []],
      ['X', 9, 9, 'lit', '=IFERROR(SMALL(IF($S$3:$S$64<>"",$S$3:$S$64),7),"")', []],
      ['X', 11, 11, 'lit', '=IFERROR(SMALL(IF($S$3:$S$64<>"",$S$3:$S$64),8),"")', []],
      ['X', 12, 12, 'lit', '=IFERROR(SMALL(IF($S$3:$S$64<>"",$S$3:$S$64),9),"")', []],
      ['X', 13, 13, 'lit', '=IFERROR(SMALL(IF($S$3:$S$64<>"",$S$3:$S$64),10),"")', []],
      ['X', 14, 14, 'lit', '=IFERROR(SMALL(IF($S$3:$S$64<>"",$S$3:$S$64),11),"")', []],
      ['X', 15, 15, 'lit', '=IFERROR(SMALL(IF($S$3:$S$64<>"",$S$3:$S$64),12),"")', []],
      ['X', 16, 16, 'lit', '=IFERROR(SMALL(IF($S$3:$S$64<>"",$S$3:$S$64),13),"")', []],
      ['X', 17, 17, 'lit', '=IFERROR(SMALL(IF($S$3:$S$64<>"",$S$3:$S$64),14),"")', []],
      ['X', 18, 18, 'lit', '=IFERROR(SMALL(IF($S$3:$S$64<>"",$S$3:$S$64),15),"")', []],
      ['X', 19, 19, 'lit', '=IFERROR(SMALL(IF($S$3:$S$64<>"",$S$3:$S$64),16),"")', []],
      ['X', 20, 20, 'lit', '=IFERROR(SMALL(IF($S$3:$S$64<>"",$S$3:$S$64),17),"")', []],
      ['X', 21, 21, 'lit', '=IFERROR(SMALL(IF($S$3:$S$64<>"",$S$3:$S$64),18),"")', []],
      ['X', 22, 22, 'lit', '=IFERROR(SMALL(IF($S$3:$S$64<>"",$S$3:$S$64),19),"")', []],
      ['X', 23, 23, 'lit', '=IFERROR(SMALL(IF($S$3:$S$64<>"",$S$3:$S$64),20),"")', []],
      ['X', 24, 24, 'lit', '=IFERROR(SMALL(IF($S$3:$S$64<>"",$S$3:$S$64),21),"")', []],
      ['X', 25, 25, 'lit', '=IFERROR(SMALL(IF($S$3:$S$64<>"",$S$3:$S$64),22),"")', []],
      ['X', 26, 26, 'lit', '=IFERROR(SMALL(IF($S$3:$S$64<>"",$S$3:$S$64),23),"")', []],
      ['X', 27, 27, 'lit', '=IFERROR(SMALL(IF($S$3:$S$64<>"",$S$3:$S$64),24),"")', []],
      ['X', 28, 28, 'lit', '=IFERROR(SMALL(IF($S$3:$S$64<>"",$S$3:$S$64),25),"")', []],
      ['X', 29, 29, 'lit', '=IFERROR(SMALL(IF($S$3:$S$64<>"",$S$3:$S$64),26),"")', []],
      ['X', 30, 30, 'lit', '=IFERROR(SMALL(IF($S$3:$S$64<>"",$S$3:$S$64),27),"")', []],
      ['X', 31, 31, 'lit', '=IFERROR(SMALL(IF($S$3:$S$64<>"",$S$3:$S$64),28),"")', []],
      ['X', 32, 32, 'lit', '=IFERROR(SMALL(IF($S$3:$S$64<>"",$S$3:$S$64),29),"")', []],
      ['X', 33, 33, 'lit', '=IFERROR(SMALL(IF($S$3:$S$64<>"",$S$3:$S$64),30),"")', []],
      ['X', 34, 34, 'lit', '=IFERROR(SMALL(IF($S$3:$S$64<>"",$S$3:$S$64),31),"")', []],
      ['X', 35, 35, 'lit', '=IFERROR(SMALL(IF($S$3:$S$64<>"",$S$3:$S$64),32),"")', []],
      ['X', 36, 36, 'lit', '=IFERROR(SMALL(IF($S$3:$S$64<>"",$S$3:$S$64),33),"")', []],
      ['X', 37, 37, 'lit', '=IFERROR(SMALL(IF($S$3:$S$64<>"",$S$3:$S$64),34),"")', []],
      ['X', 38, 38, 'lit', '=IFERROR(SMALL(IF($S$3:$S$64<>"",$S$3:$S$64),35),"")', []],
      ['X', 39, 39, 'lit', '=IFERROR(SMALL(IF($S$3:$S$64<>"",$S$3:$S$64),36),"")', []],
      ['X', 40, 40, 'lit', '=IFERROR(SMALL(IF($S$3:$S$64<>"",$S$3:$S$64),37),"")', []],
      ['Y', 3, 9, 'trans', '=IF(X3="","",INDEX($T$3:$T$64,MATCH(X3,$S$3:$S$64,0)))', []],
      ['Y', 11, 40, 'trans', '=IF(X11="","",INDEX($T$3:$T$64,MATCH(X11,$S$3:$S$64,0)))', []],
      ['Z', 3, 9, 'trans', '=IF(X3="","",INDEX($U$3:$U$64,MATCH(X3,$S$3:$S$64,0)))', []],
      ['Z', 11, 40, 'trans', '=IF(X11="","",INDEX($U$3:$U$64,MATCH(X11,$S$3:$S$64,0)))', []],
    ],
    "colfmt": {
        'S': 'mm/dd/yyyy',
        'U': '#,##0.00',
        'X': 'mm/dd/yyyy',
        'Z': '#,##0.00',
        'B': 'mm/dd/yyyy',
        'F': '#,##0.00',
        'G': '#,##0.00',
        'D': '#,##0.00',
        'K': 'mm/dd/yyyy',
        'M': '#,##0.00',
        'N': '#,##0.00',
        'O': '#,##0.00',
        'P': '#,##0.00',
    },
    "fmt_exc": {
        'S1': 'General',
        'S2': 'General',
        'U2': 'General',
        'X2': 'General',
        'Z2': 'General',
        'B4': '0.00%',
        'B5': '0.00%',
        'B6': 'General',
        'B9': 'General',
        'B10': 'General',
        'B13': 'General',
        'F13': 'General',
        'G13': 'General',
        'C14': '#,##0.00',
        'F14': 'mm/dd/yyyy',
        'C15': '#,##0.00',
        'C16': '#,##0.00',
        'C17': '#,##0.00',
        'C23': '#,##0.00',
        'U24': 'General',
        'U25': 'General',
        'U26': 'General',
        'B27': 'General',
        'D27': 'General',
        'F27': 'General',
        'G27': 'General',
        'K27': 'General',
        'M27': 'General',
        'N27': 'General',
        'O27': 'General',
        'P27': 'General',
        'U27': 'General',
        'E28': '#,##0.00',
        'U28': 'General',
        'E29': '#,##0.00',
        'U29': 'General',
        'E30': '#,##0.00',
        'U30': 'General',
        'E31': '#,##0.00',
        'U31': 'General',
        'E32': '#,##0.00',
        'U32': 'General',
        'E33': '#,##0.00',
        'U33': 'General',
        'E34': '#,##0.00',
        'U34': 'General',
        'E35': '#,##0.00',
        'U35': 'General',
        'E36': '#,##0.00',
        'U36': 'General',
        'E37': '#,##0.00',
        'U37': 'General',
        'E38': '#,##0.00',
        'U38': 'General',
        'E39': '#,##0.00',
        'U39': 'General',
        'E40': '#,##0.00',
        'U40': 'General',
    },
    "widths": {'A': 32.73, 'B': 15.45, 'C': 13.54, 'D': 15.45, 'E': 17.27, 'F': 18.18, 'G': 20.0, 'H': 15.45, 'I': 21.82, 'J': 10.82, 'K': 15.45, 'L': 13.54, 'M': 15.45, 'N': 17.27, 'O': 18.18, 'P': 20.0, 'Q': 15.45, 'R': 10.45, 'S': 13.82, 'T': 9.18, 'U': 13.82, 'V': 13.45, 'X': 10.54},
  },
}


if __name__ == "__main__":
    main()
